# Generic make file for LaTeX: requires GNU make
#
# This makefile provides four targets: dvi, ps, pdf and clean.
# The default is "pdf".
# To make a dvi file, type "make dvi"
# To make a ps file, type "make ps".
# To make a pdf file, type "make pdf" or simply "make".
# To remove all files generated by make, type "make clean".
#
# Rouben Rostmaian <rostamian@umbc.edu>
# September 2002
#
# Modified to update based on dependencies in content/ directory.
# May 2012 - djs
#

TEXFILE	= dissertation.tex

CONTENT = $(wildcard chapters/*/content/*.tex)

FIGS1 = $(wildcard chapters/*/figures/*)

FIGS2 = $(wildcard chapters/*/figures/*/*)

TABLES = $(wildcard chapters/*/tables/*)

STYLE = $(wildcard style/*)

BIB = $(wildcard *.bib)

.PHONY: dvi pdf clean
#.PHONY: pdf clean

pdf:	$(TEXFILE:.tex=.pdf)
dvi:	$(TEXFILE:.tex=.dvi)

#%.pdf: %.tex $(CONTENT) $(BIB) $(FIGS) $(TABLES) $(STYLE)
%.dvi: %.tex $(CONTENT) $(BIB) $(FIGS1) $(FIGS2) $(TABLES) $(STYLE)
	( \
	latex $<; \
	bibtex $(<:.tex=); \
	while grep -q "Rerun to get cross-references right." $(<:.tex=.log); \
	do \
		latex $<; \
	done; \
	latex $<; \
	)

%.pdf: %.dvi
	dvipdf $<

clean:
	@rm \
	$(TEXFILE:.tex=.aux) \
	$(TEXFILE:.tex=.bbl) \
	$(TEXFILE:.tex=.blg) \
	$(TEXFILE:.tex=.dvi) \
	$(TEXFILE:.tex=.lof) \
	$(TEXFILE:.tex=.log) \
	$(TEXFILE:.tex=.lot) \
	$(TEXFILE:.tex=.nlo) \
	$(TEXFILE:.tex=.out) \
	$(TEXFILE:.tex=.toc)
